### ISSUE TITLE
How do I get rid of a hotbar?

### ISSUE THREAD

**Issue by xDanub** [artulloss/Hotbar#4]
I have the main world hotbar. Then I have them select a secondary hotbar. I then use multiworld to teleport the player to a different world. They keep the secondary hotbar. I then try to give them a kit, but they either 1. Cannot move items around inventory or 2. Get Internal Server Error when they try. Please help :’(

**Comment by artulloss** [comment]
What kits plugin are you using? You should disable the lock inventory option in the world you want them to be able to move items in. Also please send the contents of the actual error; "Internal Server Error" is useless except for preventing error spam. Also if you're using advanced kits you should probably switch to the KitUI plugin because back when I was a noob at coding I added in clearing the players inventory to get rid of a hotbar.

**Comment by artulloss** [comment]
I'm adding a hotbar {clear} {player} command that will allow you to remove a hotbar, this is on the rewrite branch however the branch is unfinished and not fully functional, I expect to be done within a few days.
